### ISSUE TITLE
error on run android!

### ISSUE THREAD

**Issue by montacir** [anhtuank7c/simple-chat#1]
Hi,
Thank you for your good work :).
When I setup the project and I launch "react-native  run-android", I get:
"Objects are not valid as a React child (found; object with keys {visible}). If you meat to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of 'View'."
Where do you think the issue is?
Thanks.

**Comment by anhtuank7c** [comment]
Follow these step please:
```
git clone https://github.com/anhtuank7c/simple-chat.git
cd simple-chat
yarn (use npm install if you use npm)
```
then create your own firebase project, edit firebase config in App.js
Then run as normal.

**Comment by Sh1n1x** [comment]
Your answer is bad. Firebase info is on Login.js not in App.js and the problem with react child is already present. The problem is react-navigation code has changed with the version 1.0.0-beta.9

**Comment by anhtuank7c** [comment]
@Sh1n1x This is old one. I hope i have time to make a new series with `react-native-navigation` instead of `react-navigation` because of `low performant` issue.
